
project_id = "limzhusojiirnsefkupe"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

# Enable cron jobs for the project
[functions.cron-scheduler]
verify_jwt = false
schedule = "* * * * * *"  # Run every second
