// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mylbvrzjpwbidrqdoakk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15bGJ2cnpqcHdiaWRycWRvYWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NDk1MDQsImV4cCI6MjA1MjQyNTUwNH0.f55UyY8kRzl7RZrbmVYnIWH0nEx51B42emvLLpiE0wc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);